### ISSUE TITLE
`/account/balance`

### ISSUE THREAD

**Issue by AlanVerbner** [input-output-hk/cardano-rosetta#269]
# Description

When MA are introduced, users now can have balance in multiple tokens, not just `ÀDA` therefore when querying for an account balance also MA tokens will need to be retruned (if any).

## Implementation details

- Tokens should be returned as an extra `Amount` in the `balances` array as described [here](https://www.rosetta-api.org/docs/models/AccountBalanceResponse.html).
- When querying for transaction outputs, also `ma_tx_out` needs to be joined by `ma_tx_out.tx_out_id = tx.id`
- Token symbol is an UTF-8 hex string, check out [this query](https://github.com/input-output-hk/cardano-db-sync/issues/470#issuecomment-756295671).
- [This query](https://github.com/input-output-hk/cardano-rosetta/blob/master/cardano-rosetta-server/src/server/db/queries/blockchain-queries.ts#L216) is the one that needs to be changed. 
- **Be careful as this endpoint receives a block identifier as a filter. This means that it lets the API users to query for the balance at a certain _point in time_. The query that handles that is quite complex so be careful when changing it.**
- Do test different scenarios (balance 0, when tokens are received, when tokens are spent).

**Comment by kevinhammond** [comment]
Token symbols have a maximum size (64 bytes?).  This may be useful to know?   Note that you may need to deal with two different forms of token representation internally:

- ada-only (pre-Mary)
- ada plus other tokens (Mary and later)

I believe that the Mary implementation will use the latter representation even when the UTxO only contains ada, so you should use the new form when submitting transactions on-chain.  This is one of the things that the node "era flag" handles internally.

You may find it useful to have an operation to return a total ada-only balance, even where there native tokens present, since this is useful for eg checking administrative costs.

Note that an "account" could presumably contain a mixture of UTxO types.  To determine the total value in the account, you would need to sum values for each token type that was present (including ada) across all the UTxO.  To transfer values, you would need careful coin selection (because of the different minutxo costs for native tokens - you might need to take ada from some "payment" input if splitting a native token, for instance).

Some of these details might be hidden by the wallet backend implementation?

**Comment by kevinhammond** [comment]
Note that token names may not be UTF-8

**Comment by AlanVerbner** [comment]
> Note that token names may not be UTF-8

Ok, is there any way the clients can decode such hex strings? I mean, how do they know how to handle them?

**Comment by AlanVerbner** [comment]
>  To transfer values, you would need careful coin selection (because of the different minutxo costs for native tokens - you might need to take ada from some "payment" input if splitting a native token, for instance).

Coin selection is out of scope. That logic needs to be done by the clients as Rosetta specifies it.

**Comment by AlanVerbner** [comment]
> I believe that the Mary implementation will use the latter representation even when the UTxO only contains ada, so you should use the new form when submitting transactions on-chain. This is one of the things that the node "era flag" handles internally.

We will use [this CDDL](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley-ma/shelley-ma-test/cddl-files/shelley-ma.cddl). Is it ok?

**Comment by AlanVerbner** [comment]
> You may find it useful to have an operation to return a total ada-only balance, even where there native tokens present, since this is useful for eg checking administrative costs

We will only implement the [Rosetta Spec](https://rosetta-api.org/) API although we can add this to the backlog.

**Comment by AlanVerbner** [comment]
> Note that an "account" could presumably contain a mixture of UTxO types. To determine the total value in the account, you would need to sum values for each token type that was present (including ada) across all the UTxO. To transfer values, you would need careful coin selection (because of the different minutxo costs for native tokens - you might need to take ada from some "payment" input if splitting a native token, for instance).
> 
> Some of these details might be hidden by the wallet backend implementation?

Indeed

**Comment by kevinhammond** [comment]
> > I believe that the Mary implementation will use the latter representation even when the UTxO only contains ada, so you should use the new form when submitting transactions on-chain. This is one of the things that the node "era flag" handles internally.
> 
> We will use [this CDDL](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley-ma/shelley-ma-test/cddl-files/shelley-ma.cddl). Is it ok?

Yes, that's the latest version!

**Comment by kevinhammond** [comment]
> > You may find it useful to have an operation to return a total ada-only balance, even where there native tokens present, since this is useful for eg checking administrative costs
> 
> We will only implement the [Rosetta Spec](https://rosetta-api.org/) API although we can add this to the backlog.

That's fine, of course :)

**Comment by kevinhammond** [comment]
> > Note that token names may not be UTF-8
> 
> Ok, is there any way the clients can decode such hex strings? I mean, how do they know how to handle them?

Jared says you can decode them as UTF-8 if you like (we do this for error messages).  I think the point is that they could really be e.g. unicode so the display might be sub-optimal, but that shouldn't matter too much
